customhost = "database-1.clsyi8ewoyo8.us-east-2.rds.amazonaws.com"
customuser = "community"
custompass = "Anindya_1985"
customdb = "database-1"
custombucket = "addvolunterbucket"
customregion = "us-east-2"
